### ISSUE TITLE
Cannot input non integer values

### ISSUE THREAD

**Issue by Space-G** [JohnCorby/ow-volumetric-lights#1]
Whenever I try to input a non integer value it is always interpreted as an integer.

For example, if I input 0.025 it becomes 25.

I assume it has to do with my system language (Portuguese) using the character "," instead of "." for decimals. Changing the in-game language doesn't fix it, though.

Please let me know if I can help track down what causes the issue in any way.

**Comment by JohnCorby** [comment]
thats an owml bug. the solution is allowing menus to use ,
owml input uses the system language and not the in game language, so that's why that didn't fix it
